# https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
  "!\\[.*\\](.*)",
  "<YouTubeEmbed.*/>"
]
extend-ignore-identifiers-re = [
]

[default.extend-identifiers]

[default.extend-words]
JOD = "JOD"

[files]
extend-exclude = [
  "static/images/*",
  "openapi-spec/*",
  "code_blocks/tools/customer-center-localization.json"
]
