# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    yarn
    yarn build
  displayName: 'yarn install and build'

variables:
  - name: yarnCache
    value: $(System.DefaultWorkingDirectory)/.yarn
  - name: nodeModulesCache
    value: $(System.DefaultWorkingDirectory)/node_modules

stages:
  - template: .azure/templates/deploy_stages.yml
    parameters:
      s3_staging_bucket_url: s3://revenuecat-docs-production.revenuecat.com
      s3_production_bucket_url: s3://revenuecat-docs-staging.revenuecat.com
      s3_development_bucket_url: s3://revenuecat-docs-development.revenuecat.com
      cloudfront_staging_distribution: TBD
      cloudfront_production_distribution: TBD
      cloudfront_development_distribution: E3H8J4FFZ74FTY
      deploy_branch: refs/heads/main