stages:
  - stage: Install 
    displayName: 'Initialize Build'
    dependsOn: []
    jobs:
      - job: GetBuildInfo
        displayName: 'Get Build Information'
        pool:
          vmImage: 'ubuntu-22.04'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          - script: |
                yarn
                yarn build
              displayName: 'yarn install and build'