trigger:
  batch: true
  branches:
    include:
      - main
      - deploy-testing

pool:
  vmImage: ubuntu-latest

variables:
  - name: yarnCache
    value: $(System.DefaultWorkingDirectory)/.yarn
  - name: nodeModulesCache
    value: $(System.DefaultWorkingDirectory)/node_modules

stages:
  - template: templates/deploy_stages.yml
    parameters:
      s3_staging_bucket_url: s3://revenuecat-docs-production
      s3_production_bucket_url: s3://revenuecat-docs-staging
      s3_development_bucket_url: s3://revenuecat-docs-development
      cloudfront_staging_distribution: TBD
      cloudfront_production_distribution: TBD
      cloudfront_development_distribution: E3H8J4FFZ74FTY
      deploy_branch: refs/heads/main