# .github/workflows/doc-pr-from-webhook.yml
name: Create Docs PR from Webhook Prompt

permissions:
  contents: write
  id-token: write

on:
  repository_dispatch:
    types: [doc_update]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install Claude CLI
        run: npm install -g @anthropic-ai/claude-code
      
      - name: Run Claude
        run: |
          echo "Review the /docs folder structure and file content, and propose changes (if applicable and not already addressed in documentation) based on this prompt: ${{ github.event.client_payload.prompt }}" > prompt.txt
          mkdir -p output
          claude-code --input prompt.txt --output output
        env:
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}

      - name: Create Branch and Commit
        run: |
          branch="doc-update-${{ github.run_id }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b "$branch"
          cp -r output/* .
          git add .
          git commit -m "Update docs via Claude"
          git push origin "$branch"

      - name: Create Pull Request
        run: gh pr create --base main --head "doc-update-${{ github.run_id }}" --title "Automated Doc Update" --body "Prompt:${{github.event.client_payload.prompt}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
