# .github/workflows/doc-pr-from-webhook.yml
name: Create Docs PR from Webhook Prompt

permissions:
  contents: write
  id-token: write

on:
  repository_dispatch:
    types: [doc_update]

jobs:
  generate-docs:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Claude Code
        uses: anthropics/claude-code-action@beta
        with:
          prompt: "Review the /docs folder structure and file content, and propose changes (if applicable and not already addressed in documentation) based on this prompt: ${{ github.event.client_payload.prompt }}"
          anthropic_api_key: "${{ secrets.CLAUDE_API_KEY }}"
          output-dir: "output"

      - name: Create Branch and Commit
        run: |
          branch="doc-update-${{ github.run_id }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b "$branch"
          cp -r output/* .
          git add .
          git commit -m "Update docs via Claude"
          git push origin "$branch"

      - name: Create Pull Request
        run: gh pr create --base main --head "doc-update-${{ github.run_id }}" --title "Automated Doc Update" --body "Prompt: ${{ github.event.client_payload.prompt }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
